from enum import Enum

class Headers(Enum):
    WEIGHT = 'weight'
    BICROMIAL = 'biacromial'
    PELVIC_BREADTH = 'pelvic.breadth'
    BITROCHANTERIC = 'bitrochanteric'
    CHEST_DEPTH = 'chest.depth'
    CHEST_DIAM = 'chest.diam'
    ELBOW_DIAM = 'elbow.diam'
    WRIST_DIAM = 'wrist.diam'
    KNEE_DIAM = 'knee.diam'
    ANKLE_DIAM = 'ankle.diam'
    SHOULDER_GIRTH = 'shoulder.girth'
    CHEST_GIRTH = 'chest.girth'
    WAIST_GIRTH = 'waist.girth'
    NAVEL_GIRTH = 'navel.girth'
    HIP_GIRTH = 'hip.girth'
    THIGH_GIRTH = 'thigh.girth'
    BICEP_GIRTH = 'bicep.girth'
    FOREARM_GIRTH = 'forearm.girth'
    KNEE_GIRTH = 'knee.girth'
    CALF_GIRTH = 'calf.girth'
    ANKLE_GIRTH = 'ankle.girth'
    WRIST_GIRTH = 'wrist.girth'
    AGE = 'age'
    HEIGHT = 'height'

